### ISSUE TITLE
Missing the "Date" header field?

### ISSUE THREAD

**Issue by BraveKenny** [ideaq/meteor-email#5]
When I send email using this module, my SMTP provider warns that the sending date is missing from the email header :

`X-Amavis-Alert BAD HEADER SECTION, Missing required header field: "Date"`

Is there a way to add this header field somehow?

**Comment by BraveKenny** [comment]
Hm. It seems this is just a repo for demo example. Sorry, then!

**Comment by nelsonic** [comment]
@BraveKenny well spotted, please send a PullRequest so it can be updated! thanks!
